// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewfiglrjzombjbirwgoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3ZmlnbHJqem9tYmpiaXJ3Z29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzcwMzgsImV4cCI6MjA2NDExMzAzOH0.cvLagQLjSW7imUnsGysds2_0XnTw4fkgl0OuIabbwuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);